version: "3"
networks:
  auctiondev:
    driver: bridge
services:
  # Node code
  auctiondev:
    container_name: auctiondev
    restart: always
    build:
      context: .
      dockerfile: ./docker/dev/Dockerfile
    ports:
      - "7000:7000"
    environment:
      - NODE_ENV=development
      - PORT=7000
    volumes:
      - .:/usr/src/app
      - /usr/app/node_modules
    depends_on:
      - nginxdev
      - auctiondbdev
    links:
      - nginxdev
      - auctiondbdev
    networks:
      - auctiondev
  # Nginx
  nginxdev:
    image: nginx:alpine
    container_name: nginxdev
    restart: always
    ports:
      - "88:80"
    volumes:
      - .:/usr/src/app
      - /usr/app/node_modules
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - auctiondev
  # MongoDb
  auctiondbdev:
    container_name: auctiondbdev
    image: mongo
    ports:
      - "27017:27017"
    restart: always
    networks:
      - auctiondev
