version: "3"
services:
  api.prod:
    container_name: api.prod
    restart: always
    build:
      context: .
      dockerfile: ./docker/prod/Dockerfile
    command: export NODE_ENV=production
    ports:
      - "6000:6000"
    environment:
    - NODE_ENV=production
    - PORT=6000
    depends_on:
      - nginx-prod
    links:
      - nginx-prod
  nginx-prod:
    image: nginx:alpine
    container_name: nginx-prod
    restart: always
    ports:
      - "88:80"
    volumes:
      - .:/usr/src/app
      - /usr/app/node_modules
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf


