openapi: 3.0.0
info:
  title: 'My App APIs '
  description: MyApp V1
  version: v1
servers:
  - url: 'http://localhost:7000/api/'
    description: SwaggerHub API Auto Mocking
tags:
  - name: Auth
    description: Auth account
  - name: User
    description: Users description
  - name: Setting
    description: Category Api
  - name: Category
    description: Category Api
  - name: Check
    description: Check Api
paths:
  /auth/login:
    post:
      summary: login
      tags:
        - Auth
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Login'
      description: 'Login with username and password'
      responses:
        '200':
          description: object
        '500':
          description: Server Internal Error
  /auth/register:
    post:
      summary: register
      tags:
        - Auth
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Register'
      description: 'Register with mobile and username and password'
      responses:
        '200':
          description: object
        '500':
          description: Server Internal Error
  /auth/verify:
    put:
      summary: verify
      tags:
        - Auth
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Verify'
      description: 'sign user and resive jwt token'
      responses:
        '200':
          description: object
        '500':
          description: Server Internal Error
  /auth/otp:
    post:
      summary: otp
      tags:
        - Auth
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Otp'
      description: 'Resend code and forget password'
      responses:
        '200':
          description: object
        '500':
          description: Server Internal Error
  /users/newpassword:
    put:
      summary: newpassword
      tags:
        - User
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewPassword'
      description: 'change password but whene user has login'
      responses:
        '200':
          description: object
        '500':
          description: Server Internal Error
      security:
        - oAuth: []
  /health-check:
    get:
      tags:
        - Check
      summary: health check api
      description: ''
      responses:
        '200':
          description: Ok
        '500':
          description: Server Internal Error
  /users:
    get:
      tags:
        - User
      summary: Get all saved users
      description: List all of the users that the admin has saved
      responses:
        '200':
          description: Successful
        '204':
          description: You have No saved users
        '400':
          description: Bad request
        '401':
          description: Validating/Authenticating user (security)
        '500':
          description: Server Internal Error
      security:
        - oAuth: []
  /category:
    get:
      tags:
        - Category
      summary: Get all saved categories
      description: List all of the categories that the admin has saved
      responses:
        '200':
          description: Successful
        '204':
          description: You have No saved users
        '400':
          description: Bad request
        '500':
          description: Server Internal Error
    post:
      tags:
        - Category
      summary: new category
      description: save new categoy
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Category'
      responses:
        '200':
          description: Successful
        '204':
          description: You have No saved users
        '400':
          description: Bad request
        '500':
          description: Server Internal Error
  /setting:
    get:
      tags:
        - Setting
      summary: Get all saved setting
      description: List all of the settings that the admin has saved
      responses:
        '200':
          description: Successful
        '204':
          description: You have No saved users
        '400':
          description: Bad request
        '500':
          description: Server Internal Error
    post:
      tags:
        - Setting
      summary: new Setting
      description: save new Setting
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Setting'
      responses:
        '200':
          description: Successful
        '204':
          description: You have No saved users
        '400':
          description: Bad request
        '500':
          description: Server Internal Error
components:
  schemas:
    Verify:
      type: object
      properties:
        mobile:
          type: string
          default: "09332369461"
        code:
          type: number
          default: 9461
    NewPassword:
      type: object
      properties:
        password:
          type: string
          default: "123456"
        passwordConfirm:
          type: string
          default: "123456"
    Otp:
      type: object
      properties:
        mobile:
          type: string
          default: "09332369461"
    Register:
      type: object
      properties:
        mobile:
          type: string
          default: "09332369461"
        username:
          type: string
          default: sajadweb
        password:
          type: string
          default: password
      example:
        mobile: "09332369461"
        username: "sajadweb"
        password: "123456"
    Login:
      type: object
      properties:
        username:
          type: string
          default: react
        password:
          type: string
          default: password
    Category:
      type: object
      properties:
        title:
          type: string
          default: react
        icon:
          type: string
          default: icon
        parentId:
          type: string
          default: null
    Setting:
      type: object
      properties:
        type:
          type: string
          default: react
        content:
          type: any
          default: icon
  securitySchemes:
    oAuth:
      type: oauth2
      description: >-
        This API uses OAuth 2 with the implicit grant flow. [More
        info](https://api.example.com/docs/auth)
      flows:
        implicit:
          authorizationUrl: >-
            https://myapp.b2clogin.com/myapp.onmicrosoft.com/oauth2/v2.0/authorize?p=b2c_1_bundll
          scopes:
            openid: Open ID Connect
            'https://myapp.onmicrosoft.com/bundll/read': basic read access
            'https://myapp.onmicrosoft.com/bundll/write': basic write access
